theme: jekyll-theme-minimal
title: Joshua Shay Kricheli
description: Data Scientist at DellEMC, Computer Science M.Sc., Mechanical Engineering B.Sc., Ben Gurion University of the Negev, Israel
future: true
