theme: jekyll-theme-minimal
title: "Joshua Shay Kricheli"
logo: /assets/img/my_pic.jpg
description: "Vice President Data Science, M.Sc. in Computer Science, B.Sc. in Mechanical Engineering, Ben Gurion University of the Negev, Israel"
future: true
encoding: UTF-8
