theme: jekyll-theme-minimal
title: "Joshua Shay Kricheli"
logo: /assets/img/my_pic.jpg
description: "Senior Data Scientist, Computer Science M.Sc., Mechanical Engineering B.Sc., Ben Gurion University of the Negev, Israel"
future: true
encoding: UTF-8
